In [20]:
import pandas as pd

# Table A: Customers (Our Left Table)
customers_df = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'CustomerName': ['Ermiyas', 'Almaz', 'Yonas'],
    'ReferrerID': [2, None, 1]  # Almaz referred Ermiyas; Ermiyas referred Yonas
})

# Table B: Orders (Our Right Table)
orders_df = pd.DataFrame({
    'OrderID': [5001, 5002, 5003],
    'CustomerID': [1, 2, 99],    # Note: Customer 99 has no profile; Customer 3 has no orders
    'Item': ['Laptop', 'Smartphone', 'Keyboard'],
    'Price': [1200, 800, 45]
})

In [21]:
print("Customers")
print(customers_df)

print("\nOrders")
print(orders_df)

Customers
   CustomerID CustomerName  ReferrerID
0           1      Ermiyas         2.0
1           2        Almaz         NaN
2           3        Yonas         1.0

Orders
   OrderID  CustomerID        Item  Price
0     5001           1      Laptop   1200
1     5002           2  Smartphone    800
2     5003          99    Keyboard     45

## INNER JOIN

In [22]:
pd.merge(customers_df, orders_df, on='CustomerID', how='inner')

   CustomerID CustomerName  ReferrerID  OrderID        Item  Price
0           1      Ermiyas         2.0     5001      Laptop   1200
1           2        Almaz         NaN     5002  Smartphone    800

## LEFT JOIN

In [24]:
pd.merge(customers_df, orders_df, on='CustomerID', how='left')

   CustomerID CustomerName  ReferrerID  OrderID        Item   Price
0           1      Ermiyas         2.0   5001.0      Laptop  1200.0
1           2        Almaz         NaN   5002.0  Smartphone   800.0
2           3        Yonas         1.0      NaN         NaN     NaN

## RIGHT JOIN

In [25]:
pd.merge(customers_df, orders_df, on='CustomerID', how='right')

   CustomerID CustomerName  ReferrerID  OrderID        Item  Price
0           1      Ermiyas         2.0     5001      Laptop   1200
1           2        Almaz         NaN     5002  Smartphone    800
2          99          NaN         NaN     5003    Keyboard     45

## OUTER JOIN

In [26]:
pd.merge(customers_df, orders_df, on='CustomerID', how='outer')

   CustomerID CustomerName  ReferrerID  OrderID        Item   Price
0           1      Ermiyas         2.0   5001.0      Laptop  1200.0
1           2        Almaz         NaN   5002.0  Smartphone   800.0
2           3        Yonas         1.0      NaN         NaN     NaN
3          99          NaN         NaN   5003.0    Keyboard    45.0

## SELF JOIN

In [27]:
pd.merge(customers_df, customers_df, left_on='ReferrerID', right_on='CustomerID', suffixes=('_NewUser', '_Referrer'))

,CustomerID_NewUser,CustomerName_NewUser,ReferrerID_NewUser,CustomerID_Referrer,CustomerName_Referrer,ReferrerID_Referrer
0,1,Ermiyas,2.0,2,Almaz,NaN
1,3,Yonas,1.0,1,Ermiyas,2.0

## CROSS JOIN

In [28]:
pd.merge(customers_df, orders_df, how='cross')

,CustomerID_x,CustomerName,ReferrerID,OrderID,CustomerID_y,Item,Price
0,1,Ermiyas,2.0,5001,1,Laptop,1200
1,1,Ermiyas,2.0,5002,2,Smartphone,800
2,1,Ermiyas,2.0,5003,99,Keyboard,45
3,2,Almaz,NaN,5001,1,Laptop,1200
4,2,Almaz,NaN,5002,2,Smartphone,800
5,2,Almaz,NaN,5003,99,Keyboard,45
6,3,Yonas,1.0,5001,1,Laptop,1200
7,3,Yonas,1.0,5002,2,Smartphone,800
8,3,Yonas,1.0,5003,99,Keyboard,45